server:
  port: 8082
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:Payments;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    generate-unique-name: false
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          trace: false
          web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  springdoc:
    api-docs:
      path: /api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
resilience4j:
  circuitbreaker:
    readDeleteCircuitBreaker:
      ignoreExceptions:
        - java.lang.RuntimeException
      slidingWindowSize: 20
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      slowCallRateThreshold: 60
      slowCallDurationThreshold: 2000ms
    stateChangingCircuitBreaker:
      ignoreExceptions:
        - java.lang.RuntimeException
      slidingWindowSize: 10
      failureRateThreshold: 75
      waitDurationInOpenState: 15000
      slowCallRateThreshold: 80
      slowCallDurationThreshold: 5000ms